# Sends alert for staff members when a player join (true/false)
alert: true

# Saving type (mysql/file)
savingType: file

# Flat file setup
filename: staffnotes

# MySQL setup
mysql:
   host: localhost
   username: root
   password: root
   database: staffnotes
   port: 3306

# Edit the messages sent to the players.
# Insert [PLAYER] to display the player name used in the command in the messages.
# Intert [NOTEID] to display the note ID
messages:
    # The reload message sent
    reload: "Config have been reloaded!"

    # The reset message sent
    reset: "Staff Notes have been reset!"

    # Messages sent for /staffnotes remove <Player> <ID>
    remove:
        # The error message if the note do not exists
        error: "This note do not exists on[PLAYER]!"

        # The success message if the note was removed
        success: "Note [NOTEID] was removed from [PLAYER]!"

    # Messages sent for /staffnotes removeall <Player>
    remove-all:
        # The error message if the player do not have any notes
        error: "[PLAYER] do not have any notes!"

        # The success message when all notes from the player is removed
        success: "All notes have been removed from [PLAYER]!"

    # All the messages sent in /staffnotes show <Player>
    show:
        # Error message if the player do not have any notes
        error: "[PLAYER] do not have any notes!"

        # The info message before showing all notes
        info: "Here is the list of notes on [PLAYER]!"

        # Before showing the note ID
        note-id: "Note ID"

        # Before showing the players username
        player-name: "Player"

        # Before showing who have added the note
        added-by: "Note Added By"

        # Before showing when it was added
        date-added: "Date Added"

        # Before showing the note message
        note-message: "Note"
