name: StaffNotes
version: 1.2
main: com.shadow5353.StaffNotes
description: Make notes on players for other staff members

commands:
    staffnotes:
        usage: /<command>
        description: Main Command
        aliases: [sn, staffnote]