name: StaffNotes
version: 1.2
main: com.shadow5353.StaffNotes
description: Make notes on players for other staff members
author: hinz3
website: https://hinz3.dk/plugins/staffnotes/

commands:
    staffnotes:
        usage: /<command>
        description: Main Command
        aliases: [sn, staffnote]