name: StaffNotes
version: 1.1
main: dk.jacobhinze.StaffNotes.StaffNotes
description: Make notes on players for other staff members

commands:
    staffnotes:
        usage: /<command>
        description: Main Command
        aliases: [sn, staffnote]