# Sends alert for staff members when a player join (true/false)
alert: true

# Saving type (mysql/file)
savingType: file

# Flat file setup
filename: staffnotes.yml

# MySQL setup
mysql:
   host: localhost
   username: root
   password: root
   database: StaffNotes
   port: 3306