# Sends alert for staff members when a player join (true/false)
alert: true

# Only use this for testing functions of the plugin (true/false)
debug: false

# Saving type (mysql/file)
savingType: file

# Flat file setup
filename: staffnotes

# MySQL setup
mysql:
   host: localhost
   username: root
   password: root
   database: staffnotes
   port: 3306